"""MVP-1D — SysML -> Canonical System Model mapping tests.

Unit tests use parser-neutral synthetic snapshots (no sysml-grpc process);
integration tests load real .sysml fixtures through OpenSysMLFileAdapter
and map the resulting snapshots end-to-end.

Policy under test (docs/architecture/SYSML_TO_CANONICAL_MAPPING.md):

- root selection: explicit ``root_source_id`` (must be a named partUsage in
  the snapshot) or auto-selection from exactly one named partUsage with no
  partUsage ancestor; 0 or >1 candidates raise CanonicalMappingError;
- selected root partUsage -> System; named partUsage inside the root's
  containment subtree -> Component; outside -> DEFERRED notice;
- named actionUsage with typing evidence to an actionDef -> Function;
  without evidence (C4) -> NEEDS_RESEARCH notice, never fabricated;
- partDef / actionDef / package / other metatypes -> notices only;
- canonical ids are generated by the mapping layer, never taken from
  source identity, which is retained in SourceReference.source_element_id.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from pydantic import ValidationError

from fmea_agent.adapters.sysml import (
    CanonicalMappingError,
    CanonicalSystemMapper,
    OpenSysMLFileAdapter,
)
from fmea_agent.adapters.sysml.contracts import (
    SysMLDiagnostic,
    SysMLElementFact,
    SysMLFactSnapshot,
    SysMLSource,
    SysMLTypeFacts,
)
from fmea_agent.domain.system_model import (
    CanonicalSystemModel,
    Component,
    System,
)

MODELS_DIR = Path(__file__).resolve().parent / "fixtures" / "sysml" / "models"
VALID_MODEL = MODELS_DIR / "perform_probe.sysml"
INVALID_MODEL = MODELS_DIR / "invalid_syntax.sysml"
SIBLING_ROOTS_MODEL = MODELS_DIR / "sibling_roots_probe.sysml"
NO_USAGE_MODEL = MODELS_DIR / "no_usage_probe.sysml"


def make_source(**overrides: object) -> SysMLSource:
    data: dict[str, object] = {
        "source_type": "sysml_file",
        "source_path": "models/probe.sysml",
        "parser": "opensysml",
        "parser_version": "0.4.0",
        "runtime_version": "v0.4.3",
        "adapter": "open_sysml_file",
    }
    data.update(overrides)
    return SysMLSource.model_validate(data)


def make_element(source_id: str, metatype: str, **overrides: object) -> SysMLElementFact:
    data: dict[str, object] = {"source_id": source_id, "metatype": metatype}
    data.update(overrides)
    return SysMLElementFact.model_validate(data)


def make_snapshot(**overrides: object) -> SysMLFactSnapshot:
    data: dict[str, object] = {
        "source": make_source(),
        "elements": [],
        "relationships": [],
        "diagnostics": [],
        "load_status": "ok",
    }
    data.update(overrides)
    return SysMLFactSnapshot.model_validate(data)


def make_pump_snapshot(**overrides: object) -> SysMLFactSnapshot:
    """Synthetic stand-in for perform_probe.sysml (single candidate root)."""
    elements = [
        make_element("Pkg", "package", name="Pkg"),
        make_element("Pkg::Pump", "partDef", name="Pump", owner_id="Pkg"),
        make_element("Pkg::Motor", "partDef", name="Motor", owner_id="Pkg"),
        make_element("Pkg::Spin", "actionDef", name="Spin", owner_id="Pkg"),
        make_element(
            "Pkg::Spin::speed",
            "attributeUsage",
            name="speed",
            owner_id="Pkg::Spin",
        ),
        make_element("Pkg::pump", "partUsage", name="pump", owner_id="Pkg"),
        make_element(
            "Pkg::pump::motor",
            "partUsage",
            name="motor",
            owner_id="Pkg::pump",
        ),
        make_element(
            "Pkg::pump::motor::spin",
            "actionUsage",
            name="spin",
            owner_id="Pkg::pump::motor",
        ),
        make_element(
            "Pkg::spin",
            "actionUsage",
            name="spin",
            owner_id="Pkg",
            type_facts=SysMLTypeFacts(
                declared="Spin", resolved_id="Pkg::Spin", resolved_kind="actionDef"
            ),
        ),
    ]
    data: dict[str, object] = {
        "source": make_source(),
        "elements": elements,
        "relationships": [],
        "diagnostics": [],
        "load_status": "ok",
    }
    data.update(overrides)
    return SysMLFactSnapshot.model_validate(data)


def _notice_pairs(model: CanonicalSystemModel) -> set[tuple[str | None, str]]:
    return {(n.source_id, n.status) for n in model.notices}


# --- 1. root selection policy ---


def test_explicit_root_source_id_selects_system_root() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("A", "package", name="A"),
            make_element("A::left", "partUsage", name="left", owner_id="A"),
            make_element("A::right", "partUsage", name="right", owner_id="A"),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot, root_source_id="A::right")
    assert model.system.id == "system-1"
    assert model.system.name == "right"
    assert model.system.source_refs[0].source_element_id == "A::right"


def test_explicit_root_unknown_id_raises() -> None:
    with pytest.raises(CanonicalMappingError, match="does not reference"):
        CanonicalSystemMapper().map_snapshot(make_pump_snapshot(), root_source_id="Nope")


def test_explicit_root_non_part_usage_raises() -> None:
    with pytest.raises(CanonicalMappingError, match="must be a partUsage"):
        CanonicalSystemMapper().map_snapshot(make_pump_snapshot(), root_source_id="Pkg::Pump")


def test_explicit_root_unnamed_raises() -> None:
    snapshot = make_snapshot(elements=[make_element("A", "partUsage")])
    with pytest.raises(CanonicalMappingError, match="unnamed partUsage"):
        CanonicalSystemMapper().map_snapshot(snapshot, root_source_id="A")


# --- 2. single clear system root ---


def test_single_top_level_part_usage_becomes_system() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert model.system.id == "system-1"
    assert model.system.name == "pump"
    assert model.system.description is None


# --- 3. nested PartUsage -> Component ---


def test_nested_part_usage_maps_to_component_with_parent() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert [c.name for c in model.components] == ["motor"]
    motor = model.components[0]
    assert motor.id == "component-1"
    assert motor.parent_id == "system-1"
    assert motor.component_type is None


def test_deep_nesting_maps_parent_component_ids() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("S", "partUsage", name="s"),
            make_element("S::a", "partUsage", name="a", owner_id="S"),
            make_element("S::a::b", "partUsage", name="b", owner_id="S::a"),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    by_name = {c.name: c for c in model.components}
    assert set(by_name) == {"a", "b"}
    assert by_name["a"].parent_id == "system-1"
    assert by_name["b"].parent_id == by_name["a"].id


# --- 4. SourceReference provenance ---


def test_source_references_retain_source_identity() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    for entity in [model.system, *model.components, *model.functions]:
        assert len(entity.source_refs) == 1
        ref = entity.source_refs[0]
        assert ref.source_type == "sysml_file"
        assert ref.source_uri == "models/probe.sysml"
        assert ref.adapter == "open_sysml_file"
        assert ref.source_version is None
    assert model.system.source_refs[0].source_element_id == "Pkg::pump"
    assert model.components[0].source_refs[0].source_element_id == "Pkg::pump::motor"
    assert model.functions[0].source_refs[0].source_element_id == "Pkg::spin"


# --- 5. canonical id generation vs source identity ---


def test_canonical_ids_are_generated_and_decoupled_from_source_ids() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    ids = [model.system.id] + [c.id for c in model.components] + [f.id for f in model.functions]
    assert ids == ["system-1", "component-1", "function-1"]
    for entity in [model.system, *model.components, *model.functions]:
        assert entity.id != entity.source_refs[0].source_element_id
        assert "::" not in entity.id


def test_mapping_is_deterministic_for_the_same_snapshot() -> None:
    snapshot = make_pump_snapshot()
    first = CanonicalSystemMapper().map_snapshot(snapshot)
    second = CanonicalSystemMapper().map_snapshot(snapshot)
    assert first == second


# --- 6. typed ActionUsage -> Function ---


def test_typed_action_usage_maps_to_function() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert [f.name for f in model.functions] == ["spin"]
    function = model.functions[0]
    assert function.id == "function-1"
    assert function.allocated_to == []
    assert function.requirement_ids == []
    assert function.description is None


# --- 7. performed / untyped ActionUsage: no fabrication (C4) ---


def test_performed_action_usage_without_typing_is_not_mapped() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    function_sources = {f.source_refs[0].source_element_id for f in model.functions}
    assert "Pkg::pump::motor::spin" not in function_sources
    assert ("Pkg::pump::motor::spin", "NEEDS_RESEARCH") in _notice_pairs(model)


def test_action_usage_typed_to_non_action_def_is_not_mapped() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("S", "partUsage", name="s"),
            make_element(
                "S::calc",
                "actionUsage",
                name="calc",
                owner_id="S",
                type_facts=SysMLTypeFacts(
                    declared="Calc", resolved_id="S::Calc", resolved_kind="calculationDef"
                ),
            ),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.functions == []
    assert ("S::calc", "NEEDS_RESEARCH") in _notice_pairs(model)


# --- 8. multiple roots / no root -> CanonicalMappingError ---


def test_multiple_candidates_raise_canonical_mapping_error() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("A", "package", name="A"),
            make_element("A::left", "partUsage", name="left", owner_id="A"),
            make_element("A::right", "partUsage", name="right", owner_id="A"),
        ]
    )
    with pytest.raises(CanonicalMappingError, match="multiple PartUsage candidates"):
        CanonicalSystemMapper().map_snapshot(snapshot)


def test_multiple_candidates_error_lists_candidates() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("A", "package", name="A"),
            make_element("A::left", "partUsage", name="left", owner_id="A"),
            make_element("A::right", "partUsage", name="right", owner_id="A"),
        ]
    )
    with pytest.raises(CanonicalMappingError, match="A::left.*A::right"):
        CanonicalSystemMapper().map_snapshot(snapshot)


def test_no_candidates_raise_canonical_mapping_error() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("A", "package", name="A"),
            make_element("A::Pump", "partDef", name="Pump", owner_id="A"),
        ]
    )
    with pytest.raises(CanonicalMappingError, match="no named PartUsage candidate"):
        CanonicalSystemMapper().map_snapshot(snapshot)


def test_empty_snapshot_raises_canonical_mapping_error() -> None:
    with pytest.raises(CanonicalMappingError, match="no named PartUsage candidate"):
        CanonicalSystemMapper().map_snapshot(make_snapshot())


# --- 9. partial snapshot behavior ---


def test_partial_snapshot_maps_with_model_level_notice() -> None:
    snapshot = make_pump_snapshot(
        diagnostics=[SysMLDiagnostic(severity="error", message="expected '}'")],
        load_status="partial",
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.system.name == "pump"
    model_notices = [n for n in model.notices if n.source_id is None]
    assert len(model_notices) == 1
    assert model_notices[0].status == "NEEDS_RESEARCH"


# --- mapping rules for other metatypes ---


def test_part_definition_maps_to_needs_research_notice() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert ("Pkg::Pump", "NEEDS_RESEARCH") in _notice_pairs(model)
    assert ("Pkg::Motor", "NEEDS_RESEARCH") in _notice_pairs(model)
    notice = next(n for n in model.notices if n.source_id == "Pkg::Pump")
    assert "Component" in notice.message


def test_action_definition_maps_to_needs_research_notice() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert ("Pkg::Spin", "NEEDS_RESEARCH") in _notice_pairs(model)


def test_package_maps_to_tentative_notice() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert ("Pkg", "TENTATIVE") in _notice_pairs(model)


def test_unknown_metatype_maps_to_deferred_notice() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    assert ("Pkg::Spin::speed", "DEFERRED") in _notice_pairs(model)


def test_part_usage_outside_selected_root_subtree_gets_deferred_notice() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("A", "package", name="A"),
            make_element("A::left", "partUsage", name="left", owner_id="A"),
            make_element("A::right", "partUsage", name="right", owner_id="A"),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot, root_source_id="A::left")
    assert model.components == []
    assert ("A::right", "DEFERRED") in _notice_pairs(model)


def test_unnamed_part_usage_gets_needs_research_notice() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("S", "partUsage", name="s"),
            make_element("S::inner", "partUsage", owner_id="S"),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.components == []
    assert ("S::inner", "NEEDS_RESEARCH") in _notice_pairs(model)


def test_named_part_under_unnamed_ancestor_gets_notice() -> None:
    snapshot = make_snapshot(
        elements=[
            make_element("S", "partUsage", name="s"),
            make_element("S::wrap", "partUsage", owner_id="S"),
            make_element("S::wrap::inner", "partUsage", name="inner", owner_id="S::wrap"),
        ]
    )
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.components == []
    assert ("S::wrap", "NEEDS_RESEARCH") in _notice_pairs(model)
    assert ("S::wrap::inner", "NEEDS_RESEARCH") in _notice_pairs(model)


# --- canonical model validation ---


def test_canonical_system_model_rejects_duplicate_ids() -> None:
    with pytest.raises(ValidationError):
        CanonicalSystemModel(
            system=System(id="x", name="s"),
            components=[Component(id="x", name="c", parent_id="x")],
        )


def test_canonical_system_model_requires_parent_to_resolve() -> None:
    with pytest.raises(ValidationError):
        CanonicalSystemModel(
            system=System(id="system-1", name="s"),
            components=[Component(id="component-1", name="c", parent_id="nope")],
        )


def test_canonical_model_json_roundtrip_semantic_equality() -> None:
    model = CanonicalSystemMapper().map_snapshot(make_pump_snapshot())
    restored = CanonicalSystemModel.model_validate_json(model.model_dump_json())
    assert restored == model


# --- 10. end-to-end: real .sysml -> Snapshot -> Canonical Model ---


def test_perform_probe_maps_end_to_end() -> None:
    snapshot = OpenSysMLFileAdapter().load(VALID_MODEL)
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.system.id == "system-1"
    assert model.system.name == "hydraulicPump"
    assert (
        model.system.source_refs[0].source_element_id
        == "PerformProbe::hydraulicPump"
    )
    assert model.system.source_refs[0].source_uri == str(VALID_MODEL.resolve())
    components = {c.name: c for c in model.components}
    assert set(components) == {"motor"}
    assert components["motor"].id == "component-1"
    assert components["motor"].parent_id == "system-1"
    assert (
        components["motor"].source_refs[0].source_element_id
        == "PerformProbe::hydraulicPump::motor"
    )
    functions = {f.name: f for f in model.functions}
    assert set(functions) == {"spin"}
    assert functions["spin"].id == "function-1"
    assert (
        functions["spin"].source_refs[0].source_element_id == "PerformProbe::spin"
    )
    notice_pairs = _notice_pairs(model)
    assert ("PerformProbe", "TENTATIVE") in notice_pairs
    assert ("PerformProbe::Pump", "NEEDS_RESEARCH") in notice_pairs
    assert ("PerformProbe::Motor", "NEEDS_RESEARCH") in notice_pairs
    assert ("PerformProbe::Spin", "NEEDS_RESEARCH") in notice_pairs
    assert ("PerformProbe::Spin::speed", "DEFERRED") in notice_pairs
    assert ("PerformProbe::hydraulicPump::motor::spin", "NEEDS_RESEARCH") in notice_pairs
    assert len(model.notices) == 6
    for entity in [model.system, *model.components, *model.functions]:
        assert entity.id != entity.source_refs[0].source_element_id


def test_sibling_roots_model_requires_explicit_root() -> None:
    snapshot = OpenSysMLFileAdapter().load(SIBLING_ROOTS_MODEL)
    with pytest.raises(CanonicalMappingError, match="multiple PartUsage candidates"):
        CanonicalSystemMapper().map_snapshot(snapshot)
    model = CanonicalSystemMapper().map_snapshot(
        snapshot, root_source_id="AlphaPackage::alphaPump"
    )
    assert model.system.name == "alphaPump"
    assert [c.name for c in model.components] == ["alphaInner"]
    assert model.components[0].parent_id == "system-1"
    notice_pairs = _notice_pairs(model)
    assert ("AlphaPackage::alphaMotor", "DEFERRED") in notice_pairs
    assert ("BetaPackage::betaPump", "DEFERRED") in notice_pairs


def test_no_usage_model_raises_canonical_mapping_error() -> None:
    snapshot = OpenSysMLFileAdapter().load(NO_USAGE_MODEL)
    with pytest.raises(CanonicalMappingError, match="no named PartUsage candidate"):
        CanonicalSystemMapper().map_snapshot(snapshot)


def test_invalid_model_partial_snapshot_maps_observed_facts() -> None:
    snapshot = OpenSysMLFileAdapter().load(INVALID_MODEL)
    model = CanonicalSystemMapper().map_snapshot(snapshot)
    assert model.system.name == "broken"
    assert model.system.source_refs[0].source_element_id == "BrokenProbe::broken"
    assert any(
        n.source_id is None and n.status == "NEEDS_RESEARCH" for n in model.notices
    )
